version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: mysql-db-container
    environment:
      MYSQL_ROOT_PASSWORD: tu_contrasea
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
